### PR TITLE
Support for IMPULS protocol

### PR DESCRIPTION
**Pull request by tinco**
Hi, in the Netherlands RF lightswitches are sold by the 'Action'  for dirt cheap. Their brand is IMPULS, and their protocol a slight variation on the SARTANO protocol. I added support for them to the rfbb_cmd program, so I could control them with my raspberry pi :)

### CODE REVIEW

**Comment by tinco** [comment]
Woops, I see my vim misbehaved a little and removed pointless whitespace everywhere, I'm sorry about that. If you'd like a cleaner commit I'll make you one :)

**Comment by tandersson** [comment]
Hi!

Thanks for your pull request! I apologize for the long delay.
I could merge your request as it is, but I wonder if the IMPULS receivers use channel and unit codes?
In that case it might be good to use those as arguments (see printUsage).
What do you think about that?
The printUsage section also need to be updated with the IMPULS protocol.

**Comment by tinco** [comment]
Yeah they use 5 bits house channel and 5 bits group. And it would be good
to use those as arguments, but I'm busy with other projects at the moment.
I might come back and add that later.

**Comment by tandersson** [comment]
Added IMPULS. If anyone with access to the switches (for testing) could submit a patch that would use group/channel and also extend printUsage accordingly it would be most appreciated!

**Pull request merged**
